### ISSUE TITLE
Is this based on Chaos Monkey of Netflix/SimianArmy? 

### ISSUE THREAD

**Issue by BruceZu** [jnewland/kubernetes-pod-chaos-monkey#3]
Hi Jesse,
Excuse me, is the image kubernetes-pod-chaos-monkey  based on Chaos Monkey of Netflix/SimianArmy? 
I read through the src and if my understanding is right I think you implement it using k8s kubectl command. Right? But I am not sure about it as give it the name end up with 'chaos-monkey'.
In fact I am looking the docker image of Chaos Monkey ( Netflix/SimianArmy) used for K8s cluster.
Thank you!

**Comment by jnewland** [comment]
No, this project is an interpretation of the Netflix Chaos Monkey project for Kubernetes. When running, this project deletes random pods running in a Kubernetes cluster similar to how Netflix's project terminates EC2 instances. Sorry for the confusion!
